"""initial schema

Revision ID: 04e205d19794
Revises: 
Create Date: 2026-05-15 23:55:09.781846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e205d19794'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_defaults',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_by_username', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('path', sa.String(), nullable=True),
    sa.Column('request_id', sa.String(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_created_at'), 'audit_events', ['created_at'], unique=False)
    op.create_table('idempotency_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('expires_at', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('idem_key', sa.String(), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'method', 'path', 'idem_key')
    )
    op.create_index(op.f('ix_idempotency_responses_expires_at'), 'idempotency_responses', ['expires_at'], unique=False)
    op.create_table('login_failures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('key_hash', sa.String(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=True),
    sa.Column('first_failed_at', sa.String(), nullable=True),
    sa.Column('last_failed_at', sa.String(), nullable=True),
    sa.Column('locked_until', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('membership_plans',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price_cny', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('duration_days', sa.Integer(), nullable=False),
    sa.Column('active', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('idx_mp_active', 'membership_plans', ['active'], unique=False)
    op.create_table('payment_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_no', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan_code', sa.String(), nullable=False),
    sa.Column('amount_cny', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.Column('paid_at', sa.String(), nullable=True),
    sa.Column('provider_txn_id', sa.String(), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no')
    )
    op.create_index(op.f('ix_payment_orders_created_at'), 'payment_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_orders_status'), 'payment_orders', ['status'], unique=False)
    op.create_index(op.f('ix_payment_orders_user_id'), 'payment_orders', ['user_id'], unique=False)
    op.create_table('quote_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('material', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('volume_cm3', sa.Float(), nullable=True),
    sa.Column('weight_g', sa.Float(), nullable=True),
    sa.Column('estimated_time_h', sa.Float(), nullable=True),
    sa.Column('cost_cny', sa.Float(), nullable=True),
    sa.Column('dimensions', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_msg', sa.Text(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_history_created_at'), 'quote_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_quote_history_user_id'), 'quote_history', ['user_id'], unique=False)
    op.create_table('rate_limit_state',
    sa.Column('rate_key', sa.String(), nullable=False),
    sa.Column('bucket_json', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('rate_key')
    )
    op.create_table('slicer_presets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ext', sa.String(), nullable=False),
    sa.Column('content_b64', sa.Text(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'name')
    )
    op.create_index(op.f('ix_slicer_presets_user_id'), 'slicer_presets', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('materials', sa.Text(), nullable=True),
    sa.Column('colors', sa.Text(), nullable=True),
    sa.Column('pricing_config', sa.Text(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Integer(), nullable=True),
    sa.Column('phone_verified', sa.Integer(), nullable=True),
    sa.Column('membership_level', sa.String(), nullable=True),
    sa.Column('membership_expires_at', sa.String(), nullable=True),
    sa.Column('terms_accepted_at', sa.String(), nullable=True),
    sa.Column('privacy_accepted_at', sa.String(), nullable=True),
    sa.Column('terms_version', sa.String(), nullable=True),
    sa.Column('privacy_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('verification_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('channel', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('used_at', sa.String(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_vc_target', 'verification_codes', ['channel', 'target'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_vc_target', table_name='verification_codes')
    op.drop_table('verification_codes')
    op.drop_table('users')
    op.drop_index(op.f('ix_slicer_presets_user_id'), table_name='slicer_presets')
    op.drop_table('slicer_presets')
    op.drop_table('rate_limit_state')
    op.drop_index(op.f('ix_quote_history_user_id'), table_name='quote_history')
    op.drop_index(op.f('ix_quote_history_created_at'), table_name='quote_history')
    op.drop_table('quote_history')
    op.drop_index(op.f('ix_payment_orders_user_id'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_status'), table_name='payment_orders')
    op.drop_index(op.f('ix_payment_orders_created_at'), table_name='payment_orders')
    op.drop_table('payment_orders')
    op.drop_index('idx_mp_active', table_name='membership_plans')
    op.drop_table('membership_plans')
    op.drop_table('login_failures')
    op.drop_index(op.f('ix_idempotency_responses_expires_at'), table_name='idempotency_responses')
    op.drop_table('idempotency_responses')
    op.drop_index(op.f('ix_audit_events_created_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('app_defaults')
    # ### end Alembic commands ###
