"""Built-in printer models for slicer configuration."""

PRINTER_MODELS = [
    {
        "id": "voron_v2_250",
        "name": "Voron V2 (250mm)",
        "bed_width": 250,
        "bed_depth": 250,
        "bed_height": 250,
        "nozzle": 0.4,
        "icon": "🖨️",
    },
    {
        "id": "voron_v2_350",
        "name": "Voron V2 (350mm)",
        "bed_width": 350,
        "bed_depth": 350,
        "bed_height": 350,
        "nozzle": 0.4,
        "icon": "🖨️",
    },
    {
        "id": "bambu_a1",
        "name": "Bambu Lab A1",
        "bed_width": 256,
        "bed_depth": 256,
        "bed_height": 256,
        "nozzle": 0.4,
        "icon": "🖨️",
    },
    {
        "id": "bambu_p1s",
        "name": "Bambu Lab P1S",
        "bed_width": 256,
        "bed_depth": 256,
        "bed_height": 256,
        "nozzle": 0.4,
        "icon": "🖨️",
    },
    {
        "id": "bambu_x1c",
        "name": "Bambu Lab X1C",
        "bed_width": 256,
        "bed_depth": 256,
        "bed_height": 256,
        "nozzle": 0.4,
        "icon": "🖨️",
    },
    {
        "id": "prusa_mk4",
        "name": "Prusa MK4",
        "bed_width": 250,
        "bed_depth": 210,
        "bed_height": 220,
        "nozzle": 0.4,
        "icon": "🖨️",
    },
    {
        "id": "prusa_xl_2h",
        "name": "Prusa XL (2-head)",
        "bed_width": 360,
        "bed_depth": 360,
        "bed_height": 360,
        "nozzle": 0.4,
        "icon": "🖨️",
    },
    {
        "id": "creality_k1",
        "name": "Creality K1",
        "bed_width": 220,
        "bed_depth": 220,
        "bed_height": 250,
        "nozzle": 0.4,
        "icon": "🖨️",
    },
    {
        "id": "creality_e3v3",
        "name": "Creality Ender-3 V3",
        "bed_width": 220,
        "bed_depth": 220,
        "bed_height": 250,
        "nozzle": 0.4,
        "icon": "🖨️",
    },
    {
        "id": "anycubic_photon",
        "name": "Anycubic Photon Mono",
        "bed_width": 165,
        "bed_depth": 89,
        "bed_height": 165,
        "nozzle": 0.0,
        "icon": "✨",
    },
]
