# Bambu Lab P1S — PrusaSlicer print profile
bed_shape = 0x0,256x0,256x256,0x256
bed_temperature = 55
first_layer_bed_temperature = 55
bridge_acceleration = 3000
bridge_speed = 60
default_acceleration = 10000
external_perimeter_acceleration = 5000
external_perimeter_speed = 200
first_layer_acceleration = 2000
first_layer_speed = 45
infill_acceleration = 10000
infill_speed = 300
machine_max_acceleration_e = 5000
machine_max_acceleration_extruding = 20000
machine_max_acceleration_x = 20000
machine_max_acceleration_y = 20000
machine_max_acceleration_z = 2000
machine_max_feedrate_e = 50
machine_max_feedrate_x = 500
machine_max_feedrate_y = 500
machine_max_feedrate_z = 30
machine_max_jerk_e = 5
machine_max_jerk_x = 9
machine_max_jerk_y = 9
machine_max_jerk_z = 3
max_print_height = 256
perimeter_acceleration = 5000
perimeter_speed = 300
solid_infill_speed = 300
temperature = 220
first_layer_temperature = 220
top_solid_infill_speed = 200
travel_acceleration = 10000
travel_speed = 500
nozzle_diameter = 0.4
filament_diameter = 1.75
layer_height = 0.2
first_layer_height = 0.35
