#!/usr/bin/env python3
"""
Standalone PrusaSlicer G-code analyzer — 独立测试工具，与生产代码完全隔离。

用法:
    python gcode_analyzer.py <gcode文件路径>

输出:
    ① 文件信息（引擎版本、切片时间、文件大小）
    ② 核心切片参数（层高、喷嘴、墙层数、填充率…）
    ③ 动态运行时值（实际 HEIGHT/WIDTH 按 TYPE 分组）
    ④ 耗材用量（mm / cm³ / g）
    ⑤ 预估打印时间
    ⑥ 参数核对表（--expect layer_height=0.2 perimeters=3）

完全独立，不依赖 pricer3d 项目代码。
"""

import os
import re
import sys
from collections import defaultdict


# ══════════════════════════════════════════════════════════════════
# 解析
# ══════════════════════════════════════════════════════════════════

_FILAMENT_STATS = [
    ("filament_mm",     r"; filament used \[mm\]\s*=\s*([\d.]+)"),
    ("filament_cm3",    r"; filament used \[cm3\]\s*=\s*([\d.]+)"),
    ("filament_g",      r"; total filament used \[g\]\s*=\s*([\d.]+)"),
]

_TIME_PATTERNS = [
    # "2h 34m 12s"
    (
        r"; estimated printing time \(normal mode\)\s*=\s*(\d+)h\s+(\d+)m\s+(\d+)s",
        lambda m: int(m.group(1)) * 3600 + int(m.group(2)) * 60 + int(m.group(3)),
    ),
    # "34m 12s"
    (
        r"; estimated printing time \(normal mode\)\s*=\s*(\d+)m\s+(\d+)s",
        lambda m: int(m.group(1)) * 60 + int(m.group(2)),
    ),
]

# 行级动态值正则
_RE_HEIGHT = re.compile(r";HEIGHT:([\d.]+)")
_RE_WIDTH = re.compile(r";WIDTH:([\d.]+)")
_RE_TYPE = re.compile(r";TYPE:(.+)")


def parse_gcode(filepath: str) -> dict:
    """Parse a PrusaSlicer gcode file and return all extracted info."""
    if not os.path.exists(filepath):
        return {"error": f"文件不存在: {filepath}"}

    file_size = os.path.getsize(filepath)
    if file_size == 0:
        return {"error": "文件为空"}

    with open(filepath, "r", encoding="utf-8", errors="replace") as f:
        content = f.read()

    result: dict = {
        "file_path": os.path.abspath(filepath),
        "file_size_bytes": file_size,
        "settings": {},
        "filament": {},
        "time": {},
        "prusa_version": None,
        "slice_date": None,
        "config_settings_count": 0,
        # 动态值
        "heights": defaultdict(int),          # {height_str: count}
        "widths_by_type": defaultdict(set),   # {type_name: {width_str, ...}}
        "type_counts": defaultdict(int),       # {type_name: count}
        "layer_count": 0,
    }

    # ── Prusa 版本 & 切片日期（文件头部）──
    m = re.search(r"; generated by (.+?)\s+on\s+(.+)", content)
    if m:
        result["prusa_version"] = m.group(1)
        result["slice_date"] = m.group(2)

    # ── 挤出宽度声明 (头部) ──
    for key, pat in [
        ("external_perimeters_extrusion_width", r"; external perimeters extrusion width = (.+)"),
        ("perimeters_extrusion_width",          r"; perimeters extrusion width = (.+)"),
        ("infill_extrusion_width",              r"; infill extrusion width = (.+)"),
        ("solid_infill_extrusion_width",        r"; solid infill extrusion width = (.+)"),
        ("top_infill_extrusion_width",          r"; top infill extrusion width = (.+)"),
        ("first_layer_extrusion_width",         r"; first layer extrusion width = (.+)"),
    ]:
        m = re.search(pat, content)
        if m:
            result["settings"][key] = m.group(1).strip()

    # ── prusaslicer_config 段（文件尾部）──
    config_begin = content.find("; prusaslicer_config = begin")
    config_end = content.find("; prusaslicer_config = end")

    if config_begin != -1 and config_end != -1:
        config_section = content[config_begin:config_end]
        for line in config_section.split("\n"):
            line = line.strip()
            if not line.startswith("; ") or "=" not in line:
                continue
            stripped = line[2:].strip()
            if "=" not in stripped:
                continue
            k, v = stripped.split("=", 1)
            result["settings"][k.strip()] = v.strip()

        result["config_settings_count"] = sum(
            1 for l in config_section.split("\n")
            if l.strip().startswith("; ") and "=" in l
        )

    # ── 动态值: 逐行扫描 HEIGHT / WIDTH / TYPE ──
    current_type = None
    layer_z_set = set()
    for line in content.split("\n"):
        line = line.strip()

        # TYPE 切换
        tm = _RE_TYPE.match(line)
        if tm:
            current_type = tm.group(1)
            result["type_counts"][current_type] += 1

        # LAYER_CHANGE 计数
        if line.startswith(";LAYER_CHANGE"):
            result["layer_count"] += 1

        # HEIGHT
        hm = _RE_HEIGHT.match(line)
        if hm:
            result["heights"][hm.group(1)] += 1

        # WIDTH (绑定到当前 TYPE)
        wm = _RE_WIDTH.match(line)
        if wm and current_type:
            result["widths_by_type"][current_type].add(wm.group(1))

    # ── 耗材用量 ──
    for key, pat in _FILAMENT_STATS:
        m = re.search(pat, content)
        if m:
            try:
                result["filament"][key] = float(m.group(1))
            except ValueError:
                result["filament"][key] = m.group(1)

    # ── 预估时间 ──
    for pat, converter in _TIME_PATTERNS:
        m = re.search(pat, content)
        if m:
            total_s = converter(m)
            h = total_s // 3600
            ms = (total_s % 3600) // 60
            s = total_s % 60
            result["time"]["total_seconds"] = total_s
            result["time"]["display"] = f"{h}h {ms}m {s}s" if h else f"{ms}m {s}s"
            break

    return result


# ══════════════════════════════════════════════════════════════════
# 输出
# ══════════════════════════════════════════════════════════════════

# 核心参数: (显示名, [keys], 单位)
_CORE_PARAMS = [
    ("层高",          ["layer_height"],                                   "mm"),
    ("首层层高",      ["first_layer_height"],                             "mm"),
    ("喷嘴直径",      ["nozzle_diameter"],                                "mm"),
    ("墙层数",        ["perimeters", "wall_loops"],                       "圈"),
    ("顶部实心层",    ["top_shell_layers", "top_solid_layers"],           "层"),
    ("底部实心层",    ["bottom_shell_layers", "bottom_solid_layers"],     "层"),
    ("填充率",        ["fill_density"],                                   ""),
    ("底边宽度",      ["brim_width"],                                     "mm"),
    ("支撑",          ["support_material"],                               ""),
    ("材料直径",      ["filament_diameter"],                              "mm"),
    ("材料密度",      ["filament_density"],                               "g/cm³"),
    ("喷嘴温度",      ["temperature"],                                    "°C"),
    ("热床温度",      ["bed_temperature"],                                "°C"),
    ("打印机类型",    ["printer_technology"],                             ""),
    ("打印机型号",    ["printer_model"],                                  ""),
]

# TYPE 中文映射
_TYPE_CN = {
    "Custom": "自定义G-code",
    "Skirt/Brim": "裙边/底边",
    "Perimeter": "内墙",
    "External perimeter": "外墙",
    "Solid infill": "实心填充",
    "Internal infill": "内部填充",
    "Bridge infill": "桥接填充",
    "Top solid infill": "顶部实心填充",
    "Gap fill": "间隙填充",
    "Overhang perimeter": "悬垂外墙",
    "Support material": "支撑材料",
    "Support material interface": "支撑接触面",
}


def _get_setting(settings: dict, keys: list) -> str | None:
    for k in keys:
        v = settings.get(k)
        if v is not None:
            return v
    return None


def print_report(result: dict) -> None:
    """Pretty-print the analysis report."""
    if "error" in result:
        print(f"❌ {result['error']}")
        return

    # ── ① 文件信息 ──
    print("=" * 64)
    print("  ① 文件信息")
    print("=" * 64)
    print(f"  文件:       {result['file_path']}")
    print(f"  大小:       {result['file_size_bytes']:,} bytes")
    if result["prusa_version"]:
        print(f"  切片引擎:   {result['prusa_version']}")
    if result["slice_date"]:
        print(f"  切片时间:   {result['slice_date']}")
    print(f"  总层数:     {result['layer_count']} 层")
    print(f"  配置项数:   {result['config_settings_count']}")

    # ── ② 核心切片参数 ──
    settings = result["settings"]
    print()
    print("=" * 64)
    print("  ② 核心切片参数（config 段声明值）")
    print("=" * 64)

    for label, keys, unit in _CORE_PARAMS:
        val = _get_setting(settings, keys)
        if val is not None:
            display = f"{val} {unit}".strip()
            if keys == ["support_material"]:
                display = "是" if val in ("1", "true", "True") else "否"
            print(f"  {label:<12} {display}")
        else:
            print(f"  {label:<12} (未找到)")

    # ── ③ 动态运行时值 ──
    heights = result.get("heights", {})
    widths_by_type = result.get("widths_by_type", {})
    type_counts = result.get("type_counts", {})

    if heights or widths_by_type:
        print()
        print("=" * 64)
        print("  ③ 动态运行时值（gcode 中实际切换的值）")
        print("=" * 64)

        # 层高分布
        if heights:
            print()
            print("  📏 层高分布 (HEIGHT)")
            # 按数值排序
            for h_str in sorted(heights, key=float):
                count = heights[h_str]
                bar = "█" * min(count, 40)
                print(f"    {h_str:>10} mm  × {count:<5}  {bar}")

        # 挤出宽度 (按 TYPE 分组)
        if widths_by_type:
            print()
            print("  📐 挤出宽度 (WIDTH) 按特征类型分组")
            # 有数据的 TYPE 按出现频率排序
            ordered_types = sorted(
                widths_by_type.keys(),
                key=lambda t: type_counts.get(t, 0),
                reverse=True,
            )
            for t in ordered_types:
                w_set = widths_by_type[t]
                widths_sorted = sorted(w_set, key=float)
                cn = _TYPE_CN.get(t, t)
                count = type_counts.get(t, 0)
                if len(widths_sorted) <= 20:
                    print(f"    {cn:<16} ({count:>3}段)  →  {', '.join(widths_sorted)} mm")
                else:
                    # 太多值 → 只显示范围
                    wmin = widths_sorted[0]
                    wmax = widths_sorted[-1]
                    print(f"    {cn:<16} ({count:>3}段)  →  {wmin} ~ {wmax} mm  ({len(widths_sorted)} 种宽度)")

        # TYPE 统计
        if type_counts:
            print()
            print("  🏷️  特征类型统计")
            for t in sorted(type_counts, key=type_counts.get, reverse=True):
                cn = _TYPE_CN.get(t, t)
                count = type_counts[t]
                bar = "█" * min(count // 2, 30)
                print(f"    {cn:<18} {count:>4} 段  {bar}")

    # ── ④ 耗材 ──
    fil = result["filament"]
    if fil:
        print()
        print("=" * 64)
        print("  ④ 耗材用量")
        print("=" * 64)
        if "filament_mm" in fil:
            print(f"  线长:    {fil['filament_mm']:>10.2f} mm  ({fil['filament_mm']/1000:.2f} m)")
        if "filament_cm3" in fil:
            print(f"  体积:    {fil['filament_cm3']:>10.2f} cm³")
        if "filament_g" in fil:
            print(f"  重量:    {fil['filament_g']:>10.2f} g")
            # 校验 密度×体积=重量
            density_str = _get_setting(settings, ["filament_density"])
            try:
                density = float(density_str) if density_str else 0
            except ValueError:
                density = 0
            if density > 0 and "filament_cm3" in fil:
                expected_g = fil["filament_cm3"] * density
                if abs(expected_g - fil["filament_g"]) > 0.01:
                    print(f"           ⚠️  密度{density} × 体积{fil['filament_cm3']} = {expected_g:.2f}g，"
                          f"与 gcode 声明 ({fil['filament_g']}g) 不一致")

    # ── ⑤ 时间 ──
    t = result["time"]
    if t:
        print()
        print("=" * 64)
        print("  ⑤ 预估时间")
        print("=" * 64)
        print(f"  时间:    {t.get('display', 'N/A')}")
        if "total_seconds" in t:
            mins = t["total_seconds"] / 60
            print(f"  总计:    {t['total_seconds']} 秒 ({mins:.1f} 分钟)")

    print()


def print_verify_table(result: dict, expected: list) -> None:
    """对比期望值 vs 实际值，输出核对表."""
    if "error" in result:
        return

    settings = result["settings"]
    print("=" * 64)
    print("  ⑥ 参数核对")
    print("=" * 64)
    print(f"  {'参数':<16} {'期望':>8}  {'实际':>8}  结果")
    print(f"  {'─'*16} {'─'*8}  {'─'*8}  {'─'*6}")

    all_ok = True
    for label, key, expected_val in expected:
        actual_val = settings.get(key)
        ok = actual_val is not None and str(actual_val) == str(expected_val)
        if not ok:
            all_ok = False
        actual_display = str(actual_val) if actual_val is not None else "(缺失)"
        icon = "✅" if ok else "❌"
        print(f"  {label:<16} {expected_val:>8}  {actual_display:>8}  {icon}")

    print()
    if all_ok:
        print("  🎉 所有参数匹配！")
    else:
        print("  ⚠️  存在不匹配的参数，请检查用户中心 → 切片参数传递链路。")
    print()


# ══════════════════════════════════════════════════════════════════
# CLI
# ══════════════════════════════════════════════════════════════════

if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("用法: python gcode_analyzer.py <gcode文件路径> [--expect k=v ...]")
        print()
        print("示例:")
        print("  python gcode_analyzer.py test.gcode")
        print("  python gcode_analyzer.py test.gcode --expect layer_height=0.2 perimeters=3")
        sys.exit(1)

    filepath = sys.argv[1]

    expected = []
    args = sys.argv[2:]
    i = 0
    while i < len(args):
        if args[i] == "--expect":
            i += 1
            continue
        if "=" in args[i]:
            k, v = args[i].split("=", 1)
            expected.append((k, k, v))
        i += 1

    result = parse_gcode(filepath)
    print_report(result)

    if expected:
        print_verify_table(result, expected)
